default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages:
  - pre-commit

repos:

  - repo: builtin
    hooks:
      - id: check-case-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.22.0
    hooks:
      - id: markdownlint-cli2
        args:
          - --config
          - .markdownlint.yaml
          - --fix
        exclude: '^(CHANGELOG.md)$'

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.3
    hooks:
      - id: uv-lock
      - id: uv-sync

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: run tests
        entry: uv run pytest tests/
        language: system
        pass_filenames: false
        verbose: true
      - id: ty-check
        name: ty-check
        language: system
        entry: uv run ty check
        types:
          - python
